### ISSUE TITLE
[Bug]fail to show the POP account's font color at Thread Pane

### ISSUE THREAD

**Issue by Yusei-StarDust** [Vigilans/accountcolors#10]
As title, but strangely POP account's background color at Thread Pane could be shown correctly.

**Comment by Vigilans** [comment]
Fixed by #11.

In fact POP account's background color also do not show correctly (

You are possibly enabling `Color Pane Background` which could correctly detect color information for a POP server.

You can download the fixed addon here: https://github.com/Vigilans/accountcolors/releases/download/tb-115-v3/accountcolors.zip
