### ISSUE TITLE
[Feature] Thread Pane background color setting

### ISSUE THREAD

**Issue by MIOsystems** [Vigilans/accountcolors#3]
For the best and most subtle color indication it would be great to change the color of the hole thread pane instead of the rows.

**Comment by Vigilans** [comment]
Do you mean also color the thread header?

**Comment by MIOsystems** [comment]
Not necessarily. Meanly the list view pane. 

Now looks like this:

![Thread pane](https://github.com/Vigilans/accountcolors/assets/46918729/1f4afeb7-365c-46ef-ad89-6d946635ae47)

**Comment by Vigilans** [comment]
Umm, what color to fill when in united folder? 

There is indeed code related to your feature: `Light Pane Background` and `Dark Pane Background`, so by reusing their logic maybe `Color Raw Background` can at least color according to current folder's identity (And leave unified folder uncolored?).

**Comment by MIOsystems** [comment]
Your suggestion feel logical. In the unified folder the row colorization is logic. The coloring of the hole thread pane feels way more solid and integrated. If you see an easy implementation for that it would be great.

**Comment by Vigilans** [comment]
Coloring the whole thread pane (including the thread pane header) seems not easy to implement, because the header color is subtly different with the background color, and the line separator's color is hard to decide.

I think a new option is necessary for your feature. It should be named as `Color Pane Background (Except in Unified Folder)`.

And, for https://github.com/Vigilans/accountcolors/issues/4, the option should be named as `Color Row Background as Gradient from [Left/Right to Right/Left]`. Are you familiar with CSS and can provide your desirable `linear-gradient` style expression?

**Comment by MIOsystems** [comment]
I see no effect of the `Light Pane Background` setting. Should this setting do with i described?

**Comment by Vigilans** [comment]
You can try `Dark Pane Background` if you're on a light theme. `Dark/Light Pane Background` will use a subtle different color for thread pane header (e.g. `rgb(250,250,250)` for header and `rgb(255,255,255)` for background).

**Comment by MIOsystems** [comment]
I feel it is an easy job (hard for me) to add `Color Pane Background` to the settings to achieve a full colorization like i suggest.

**Comment by Vigilans** [comment]
Implemented in #7.
